---
filename: config_files.yaml
enabled: true
meta:
  name: Config Files
  author: PaperMtn
  date: '2020-08-14'
  description: Detects exposed configuration files
  severity: '30'
category: files
scope:
- files
file_types:
test_cases:
  match_cases:
  - blank
  fail_cases:
  - blank
strings:
- '".conf"'
- '".ini"'
pattern: ''
